import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from "axios";

const Todo = ({todo}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Perfil de todo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Perfil de todo {todo.nombre} {todo.apellido}
        </h1><br />
        <Link href="/todos">Volver a todos</Link>
          <p>
            <span>Tarea:</span> {todo.nombre}<br />
            <span>Fecha entrega:</span> {todo.apellido}<br />
          </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps(context) {
  const { data } = await axios.get('http://localhost:3000/api/todo?id=' + context.query.id);
 
  return {
    props: {
      todo: data
    }
  }
}

export default Todo