import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from "axios";

const Todos = ({todos}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Estos son nuestros todos
        </h1><br />
        <Link href="/">Volver a la home</Link>
        <p>
          {todos.map((todo) => (
            <p key={todo.nombre}>
              <span>Tarea:</span> {todo.nombre}<br />
              <span>Fecha entrega:</span> {todo.apellido}<br />
              <span>Explicacion:</span> {todo.explicacion}<br />
              <Link href={`/todo?id=${todo.id}`}>Ver tarea</Link>
            </p>
          ))}
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps(context) {
  const { data } = await axios.get('http://localhost:3000/api/todos');
  console.info("EJECUTO!")
 
  return {
    props: {
      todos: data
    }
  }
}

export default Todos